# Generated by Django 3.0.8 on 2021-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('nb_heure', models.FloatField()),
                ('intervenant', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
