# Generated by Django 3.0.8 on 2021-02-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'managed': False},
        ),
    ]
